#include "audio_editor/AudioEditorModule.h"
#include "audio_editor/EditorAudioEffects.h"
#include "audio_editor/EditorAudioImportDiagnostics.h"
#include "audio_editor/EditorAudioTarget.h"
#include "audio_editor/EditorAudioTransport.h"
#include "audio_editor/EditorAudioWaveform.h"
