#include "animation/ProceduralBoneConfig.h"

#include "animation/AnimSkeleton.h"
#include "animation/DynamicBoneSolver.h"
#include "animation/FootIKSolver.h"
#include "common/Diagnostic.h"

#include <cmath>
#include <set>

namespace eve::animation {
namespace {
template<class T> Result<T> invalid(std::string message,std::string path){return Result<T>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,std::move(message),std::move(path)));}
Result<void> invalid(std::string message,std::string path){return Result<void>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,std::move(message),std::move(path)));}
const Value* field(const Value& value,const char* name){return value.find(name);}
bool number(const Value& object,const char* name,float& out){const Value* value=field(object,name);if(!value||(!value->isInt64()&&!value->isDouble()))return false;out=static_cast<float>(value->isInt64()?value->asInt():value->asDouble());return std::isfinite(out);}
bool integer(const Value& object,const char* name,int& out){const Value* value=field(object,name);if(!value||!value->isInt64())return false;out=static_cast<int>(value->asInt());return true;}
bool boolean(const Value& object,const char* name,bool& out){const Value* value=field(object,name);if(!value||!value->isBool())return false;out=value->asBool();return true;}
bool string(const Value& object,const char* name,std::string& out){const Value* value=field(object,name);if(!value||!value->isString())return false;out=value->asString();return true;}
Value particleValue(const DynamicBoneParticleConfig& p){Value::Object o;o["stiffness"]=p.stiffness;o["damping"]=p.damping;o["inertia"]=p.inertia;o["gravityScale"]=p.gravityScale;o["radius"]=p.radius;return Value(std::move(o));}
}

Result<void> DynamicBoneConfig::validate() const {
    auto unit=[](float v){return std::isfinite(v)&&v>=0.f&&v<=1.f;};
    if(!unit(weight)||!unit(objectMoveResponse)||!std::isfinite(updateRate)||updateRate<0.f||!std::isfinite(teleportThreshold)||teleportThreshold<0.f||!std::isfinite(distanceLimit)||distanceLimit<0.f)return invalid("invalid global dynamic-bone parameter","dynamicBone");
    std::set<std::pair<std::string,std::string>> roots;
    for(size_t i=0;i<chains.size();++i){const auto& c=chains[i];if(c.rootBone.empty()||c.endBone.empty()||!roots.emplace(c.rootBone,c.endBone).second||!unit(c.stiffness)||!unit(c.damping)||!unit(c.inertia)||c.radius<0.f||c.iterations<1||c.freezeAxis<0||c.freezeAxis>3||c.endMode<0||c.endMode>2)return invalid("invalid or duplicate chain","chains["+std::to_string(i)+"]");for(const auto& p:c.particles)if(!unit(p.stiffness)||!unit(p.damping)||!unit(p.inertia)||p.radius<0.f)return invalid("invalid particle profile","chains.particles");}
    for(size_t i=0;i<colliders.size();++i)if(!std::isfinite(colliders[i].radius)||colliders[i].radius<=0.f)return invalid("invalid collider radius","colliders["+std::to_string(i)+"].radius");
    if(footIK.enabled){if(footIK.pelvisBone.empty()||footIK.left.hip.empty()||footIK.left.knee.empty()||footIK.left.foot.empty()||footIK.maxPelvisOffset<0.f||footIK.minGroundNormalY<0.f||footIK.minGroundNormalY>1.f||footIK.positionResponse<0.f||footIK.rotationResponse<0.f||footIK.groundStartHeight<0.f||footIK.groundQueryDistance<0.f||footIK.contactGraceTime<0.f||footIK.lockEnterWeight<0.f||footIK.lockEnterWeight>1.f||footIK.lockExitWeight<0.f||footIK.lockExitWeight>footIK.lockEnterWeight)return invalid("invalid Foot IK configuration","footIK");}
    return Result<void>::success();
}

Result<Value> DynamicBoneConfig::toValue() const {
    auto valid=validate();if(!valid)return Result<Value>::failure(valid.status());
    Value::Object root=unknownFields;root["schema"]=std::string(SchemaId);root["schemaVersion"]=static_cast<std::int64_t>(SchemaVersion);
    root["gravityX"]=gravityX;root["gravityY"]=gravityY;root["gravityZ"]=gravityZ;root["externalX"]=externalX;root["externalY"]=externalY;root["externalZ"]=externalZ;root["weight"]=weight;root["updateRate"]=updateRate;root["teleportThreshold"]=teleportThreshold;root["objectMoveResponse"]=objectMoveResponse;root["distanceLimit"]=distanceLimit;
    Value::Array chainValues;for(const auto& c:chains){Value::Object o;o["rootBone"]=c.rootBone;o["endBone"]=c.endBone;o["stiffness"]=c.stiffness;o["damping"]=c.damping;o["inertia"]=c.inertia;o["gravityScale"]=c.gravityScale;o["radius"]=c.radius;o["iterations"]=static_cast<std::int64_t>(c.iterations);o["freezeAxis"]=static_cast<std::int64_t>(c.freezeAxis);o["selfCollision"]=c.selfCollision;o["endMode"]=static_cast<std::int64_t>(c.endMode);o["endLength"]=c.endLength;o["endX"]=c.endX;o["endY"]=c.endY;o["endZ"]=c.endZ;Value::Array particles;for(const auto& p:c.particles)particles.push_back(particleValue(p));o["particles"]=Value(std::move(particles));chainValues.emplace_back(std::move(o));}root["chains"]=Value(std::move(chainValues));
    Value::Array colliderValues;for(const auto& c:colliders){Value::Object o;o["bone"]=c.bone;o["startX"]=c.startX;o["startY"]=c.startY;o["startZ"]=c.startZ;o["endX"]=c.endX;o["endY"]=c.endY;o["endZ"]=c.endZ;o["radius"]=c.radius;o["capsule"]=c.capsule;o["inside"]=c.inside;o["enabled"]=c.enabled;colliderValues.emplace_back(std::move(o));}root["colliders"]=Value(std::move(colliderValues));
    auto legValue=[](const FootIKLegConfig& leg){Value::Object o;o["hip"]=leg.hip;o["knee"]=leg.knee;o["foot"]=leg.foot;o["toe"]=leg.toe;o["soleOffset"]=leg.soleOffset;o["toeSoleOffset"]=leg.toeSoleOffset;return Value(std::move(o));};Value::Object foot;foot["enabled"]=footIK.enabled;foot["footLockEnabled"]=footIK.footLockEnabled;foot["pelvisBone"]=footIK.pelvisBone;foot["left"]=legValue(footIK.left);foot["right"]=legValue(footIK.right);foot["maxPelvisOffset"]=footIK.maxPelvisOffset;foot["minGroundNormalY"]=footIK.minGroundNormalY;foot["positionResponse"]=footIK.positionResponse;foot["rotationResponse"]=footIK.rotationResponse;foot["groundStartHeight"]=footIK.groundStartHeight;foot["groundQueryDistance"]=footIK.groundQueryDistance;foot["contactGraceTime"]=footIK.contactGraceTime;foot["lockEnterWeight"]=footIK.lockEnterWeight;foot["lockExitWeight"]=footIK.lockExitWeight;root["footIK"]=Value(std::move(foot));
    return Result<Value>::success(Value(std::move(root)));
}

Result<DynamicBoneConfig> DynamicBoneConfig::fromValue(const Value& value) {
    if(!value.isObject())return invalid<DynamicBoneConfig>("expected object","dynamicBone");
    DynamicBoneConfig out;
    std::string schema;int version=0;if(!string(value,"schema",schema)||schema!=SchemaId)return invalid<DynamicBoneConfig>("unexpected schema","schema");if(!integer(value,"schemaVersion",version)||version!=static_cast<int>(SchemaVersion))return invalid<DynamicBoneConfig>("unsupported schema version","schemaVersion");
    if(!number(value,"gravityX",out.gravityX)||!number(value,"gravityY",out.gravityY)||!number(value,"gravityZ",out.gravityZ)||!number(value,"externalX",out.externalX)||!number(value,"externalY",out.externalY)||!number(value,"externalZ",out.externalZ)||!number(value,"weight",out.weight)||!number(value,"updateRate",out.updateRate)||!number(value,"teleportThreshold",out.teleportThreshold)||!number(value,"objectMoveResponse",out.objectMoveResponse)||!number(value,"distanceLimit",out.distanceLimit))return invalid<DynamicBoneConfig>("missing numeric global field","dynamicBone");
    const Value* chainArray=field(value,"chains");const Value* colliderArray=field(value,"colliders");const Value* foot=field(value,"footIK");if(!chainArray||!chainArray->isArray()||!colliderArray||!colliderArray->isArray()||!foot||!foot->isObject())return invalid<DynamicBoneConfig>("expected chain, collider and Foot IK values","dynamicBone");
    for(const auto& item:*chainArray->getIf<Value::Array>()){if(!item.isObject())return invalid<DynamicBoneConfig>("expected chain object","chains");DynamicBoneChainConfig c;if(!string(item,"rootBone",c.rootBone)||!string(item,"endBone",c.endBone)||!number(item,"stiffness",c.stiffness)||!number(item,"damping",c.damping)||!number(item,"inertia",c.inertia)||!number(item,"gravityScale",c.gravityScale)||!number(item,"radius",c.radius)||!integer(item,"iterations",c.iterations)||!integer(item,"freezeAxis",c.freezeAxis)||!boolean(item,"selfCollision",c.selfCollision)||!integer(item,"endMode",c.endMode)||!number(item,"endLength",c.endLength)||!number(item,"endX",c.endX)||!number(item,"endY",c.endY)||!number(item,"endZ",c.endZ))return invalid<DynamicBoneConfig>("invalid chain field","chains");const Value* profiles=field(item,"particles");if(!profiles||!profiles->isArray())return invalid<DynamicBoneConfig>("expected particle array","chains.particles");for(const auto& profile:*profiles->getIf<Value::Array>()){DynamicBoneParticleConfig p;if(!profile.isObject()||!number(profile,"stiffness",p.stiffness)||!number(profile,"damping",p.damping)||!number(profile,"inertia",p.inertia)||!number(profile,"gravityScale",p.gravityScale)||!number(profile,"radius",p.radius))return invalid<DynamicBoneConfig>("invalid particle","chains.particles");c.particles.push_back(p);}out.chains.push_back(std::move(c));}
    for(const auto& item:*colliderArray->getIf<Value::Array>()){if(!item.isObject())return invalid<DynamicBoneConfig>("expected collider object","colliders");DynamicBoneColliderConfig c;if(!string(item,"bone",c.bone)||!number(item,"startX",c.startX)||!number(item,"startY",c.startY)||!number(item,"startZ",c.startZ)||!number(item,"endX",c.endX)||!number(item,"endY",c.endY)||!number(item,"endZ",c.endZ)||!number(item,"radius",c.radius)||!boolean(item,"capsule",c.capsule)||!boolean(item,"inside",c.inside)||!boolean(item,"enabled",c.enabled))return invalid<DynamicBoneConfig>("invalid collider field","colliders");out.colliders.push_back(std::move(c));}
    if(!boolean(*foot,"enabled",out.footIK.enabled)||!boolean(*foot,"footLockEnabled",out.footIK.footLockEnabled)||!string(*foot,"pelvisBone",out.footIK.pelvisBone)||!number(*foot,"maxPelvisOffset",out.footIK.maxPelvisOffset)||!number(*foot,"minGroundNormalY",out.footIK.minGroundNormalY)||!number(*foot,"positionResponse",out.footIK.positionResponse)||!number(*foot,"rotationResponse",out.footIK.rotationResponse)||!number(*foot,"groundStartHeight",out.footIK.groundStartHeight)||!number(*foot,"groundQueryDistance",out.footIK.groundQueryDistance)||!number(*foot,"contactGraceTime",out.footIK.contactGraceTime)||!number(*foot,"lockEnterWeight",out.footIK.lockEnterWeight)||!number(*foot,"lockExitWeight",out.footIK.lockExitWeight))return invalid<DynamicBoneConfig>("invalid Foot IK field","footIK");
    auto decodeLeg=[&](const char* name,FootIKLegConfig& leg){const Value* item=field(*foot,name);return item&&item->isObject()&&string(*item,"hip",leg.hip)&&string(*item,"knee",leg.knee)&&string(*item,"foot",leg.foot)&&string(*item,"toe",leg.toe)&&number(*item,"soleOffset",leg.soleOffset)&&number(*item,"toeSoleOffset",leg.toeSoleOffset);};if(!decodeLeg("left",out.footIK.left)||!decodeLeg("right",out.footIK.right))return invalid<DynamicBoneConfig>("invalid Foot IK leg","footIK");
    out.unknownFields=*value.getIf<Value::Object>();for(const char* key:{"schema","schemaVersion","gravityX","gravityY","gravityZ","externalX","externalY","externalZ","weight","updateRate","teleportThreshold","objectMoveResponse","distanceLimit","chains","colliders","footIK"})out.unknownFields.erase(key);
    auto valid=out.validate();if(!valid)return Result<DynamicBoneConfig>::failure(valid.status());return Result<DynamicBoneConfig>::success(std::move(out));
}

Result<void> DynamicBoneConfig::apply(AnimSkeleton& skeleton,DynamicBoneSolver& solver) const {
    auto valid=validate();if(!valid)return valid;DynamicBoneSolver candidate(&skeleton);candidate.setGlobalGravity(gravityX,gravityY,gravityZ);candidate.setExternalForce(externalX,externalY,externalZ);candidate.setWeight(weight);candidate.setUpdateRate(updateRate);candidate.setTeleportThreshold(teleportThreshold);candidate.setObjectMoveResponse(objectMoveResponse);candidate.setDistanceLimit(distanceLimit);
    for(const auto& c:chains){const int chain=candidate.addChainByName(c.rootBone,c.endBone,c.stiffness,c.damping,c.inertia,c.gravityScale,c.radius,c.iterations);if(chain<0)return invalid("chain bone path cannot be resolved",c.rootBone+"->"+c.endBone);candidate.setChainFreezeAxis(chain,c.freezeAxis);candidate.setChainSelfCollision(chain,c.selfCollision);if(c.endMode==1)candidate.setChainEndLength(chain,c.endLength);else if(c.endMode==2)candidate.setChainEndOffset(chain,c.endX,c.endY,c.endZ);for(size_t i=0;i<c.particles.size();++i){const auto& p=c.particles[i];candidate.setChainParticleParameters(chain,static_cast<int>(i),p.stiffness,p.damping,p.inertia,p.gravityScale,p.radius);}}
    for(const auto& c:colliders){const int bone=c.bone.empty()?-1:skeleton.findBone(c.bone);if(!c.bone.empty()&&bone<0)return invalid("collider bone cannot be resolved",c.bone);if(c.capsule){if(bone<0)candidate.addColliderCapsule(c.startX,c.startY,c.startZ,c.endX,c.endY,c.endZ,c.radius);else candidate.addBoneColliderCapsule(bone,c.startX,c.startY,c.startZ,c.endX,c.endY,c.endZ,c.radius);}else{if(bone<0)candidate.addColliderSphere(c.startX,c.startY,c.startZ,c.radius);else candidate.addBoneColliderSphere(bone,c.startX,c.startY,c.startZ,c.radius);}const int index=candidate.getColliderCount()-1;candidate.setColliderInside(index,c.inside);candidate.setColliderEnabled(index,c.enabled);}
    solver=candidate;return Result<void>::success();
}

Result<void> DynamicBoneConfig::apply(AnimSkeleton& skeleton,DynamicBoneSolver& dynamicSolver,FootIKSolver& footSolver) const {
    DynamicBoneSolver dynamicCandidate(&skeleton);auto dynamicResult=apply(skeleton,dynamicCandidate);if(!dynamicResult)return dynamicResult;
    FootIKSolver footCandidate(&skeleton);if(footIK.enabled){const int pelvis=skeleton.findBone(footIK.pelvisBone);const int lh=skeleton.findBone(footIK.left.hip),lk=skeleton.findBone(footIK.left.knee),lf=skeleton.findBone(footIK.left.foot);if(pelvis<0||lh<0||lk<0||lf<0)return invalid("Foot IK bone cannot be resolved","footIK.left");footCandidate.setPelvisBone(pelvis);footCandidate.configureLeftLeg(lh,lk,lf,footIK.left.soleOffset);if(!footIK.left.toe.empty()){const int toe=skeleton.findBone(footIK.left.toe);if(toe<0)return invalid("left toe cannot be resolved","footIK.left.toe");footCandidate.configureLeftToe(toe,footIK.left.toeSoleOffset);}if(!footIK.right.hip.empty()||!footIK.right.knee.empty()||!footIK.right.foot.empty()){const int rh=skeleton.findBone(footIK.right.hip),rk=skeleton.findBone(footIK.right.knee),rf=skeleton.findBone(footIK.right.foot);if(rh<0||rk<0||rf<0)return invalid("right leg cannot be resolved","footIK.right");footCandidate.configureRightLeg(rh,rk,rf,footIK.right.soleOffset);if(!footIK.right.toe.empty()){const int toe=skeleton.findBone(footIK.right.toe);if(toe<0)return invalid("right toe cannot be resolved","footIK.right.toe");footCandidate.configureRightToe(toe,footIK.right.toeSoleOffset);}}footCandidate.setMaxPelvisOffset(footIK.maxPelvisOffset);footCandidate.setMinGroundNormalY(footIK.minGroundNormalY);footCandidate.setPositionResponse(footIK.positionResponse);footCandidate.setRotationResponse(footIK.rotationResponse);footCandidate.setGroundQuery(footIK.groundStartHeight,footIK.groundQueryDistance);footCandidate.setContactGraceTime(footIK.contactGraceTime);footCandidate.setFootLockThresholds(footIK.lockEnterWeight,footIK.lockExitWeight);footCandidate.setFootLockEnabled(footIK.footLockEnabled);}
    dynamicSolver=dynamicCandidate;footSolver=footCandidate;return Result<void>::success();
}
}
