#include "editor/EditorBiomeTarget.h"
#include "procgen/Biome.h"
#include "procgen/SpatialData.h"
#include <cmath>
#include <utility>
namespace eve::editor{namespace{template<class T>EditorResult<T>fail(EditorStatus s,const char*r,std::string m){return EditorResult<T>::error(s,RuleId(r),std::move(m));}}
BiomeDocumentRuntime::BiomeDocumentRuntime()=default;BiomeDocumentRuntime::~BiomeDocumentRuntime()=default;
EditorResult<void>BiomeDocumentRuntime::publish(const BiomeDocumentTarget&document,const IBiomeSpatialResolver&resolver){const auto diagnostics=document.validate();for(const auto&d:diagnostics)if(d.severity==DiagnosticSeverity::Error){EditorResult<void>r;r.status=EditorStatus::Rejected;r.diagnostics=diagnostics;return r;}auto candidate=std::make_unique<procgen::BiomeRules>();for(const auto&layer:document.layers()){auto spatial=resolver.resolve(layer.spatialAsset);if(!spatial.value||!*spatial.value){EditorResult<void>failed;failed.status=spatial.status;failed.diagnostics=std::move(spatial.diagnostics);return failed;}if(!candidate->addLayer(layer.name,*spatial.value,layer.priority,layer.density))return fail<void>(EditorStatus::Failed,"editor.biome.runtime-layer","Biome runtime rejected a validated layer");for(const auto&asset:layer.assets)if(!candidate->addAsset(layer.name,asset.asset,asset.weight,asset.minScale,asset.maxScale,asset.randomYaw))return fail<void>(EditorStatus::Failed,"editor.biome.runtime-asset","Biome runtime rejected a validated asset");}for(const auto&ref:document.exclusions()){auto spatial=resolver.resolve(ref);if(!spatial.value||!*spatial.value){EditorResult<void>failed;failed.status=spatial.status;failed.diagnostics=std::move(spatial.diagnostics);return failed;}if(!candidate->addExclusion(*spatial.value))return fail<void>(EditorStatus::Failed,"editor.biome.runtime-exclusion","Biome runtime rejected a validated exclusion");}rules_=std::move(candidate);revision_=document.revision();EditorResult<void>result=EditorResult<void>::applied();result.diagnostics=diagnostics;return result;}
EditorResult<std::unique_ptr<procgen::PointSet>>BiomeDocumentRuntime::preview(procgen::SpatialData*domain,float spacing,std::uint32_t seed,float jitter,Revision expectedRevision){if(expectedRevision!=revision_)return fail<std::unique_ptr<procgen::PointSet>>(EditorStatus::Conflict,"editor.biome.stale","Biome preview generation is stale");if(!rules_||!domain||!std::isfinite(spacing)||spacing<=0||!std::isfinite(jitter)||jitter<0||jitter>1)return fail<std::unique_ptr<procgen::PointSet>>(EditorStatus::Rejected,"editor.biome.preview","Biome preview inputs are invalid");std::unique_ptr<procgen::PointSet>points(rules_->generate(domain,spacing,seed,jitter));if(!points)return fail<std::unique_ptr<procgen::PointSet>>(EditorStatus::Failed,"editor.biome.generate",rules_->getError());return EditorResult<std::unique_ptr<procgen::PointSet>>::applied(std::move(points));}
} // namespace eve::editor
