#include "scene/PcgBuildConfig.h"
#include "common/SquirrelBinding.h"
#include <simplesquirrel/simplesquirrel.hpp>
namespace eve::scene { namespace {  }
Result<void> PcgBuildConfig::setPublicationType(int type){if(type<0||type>1)return Result<void>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"publication type must be 0 or 1",{}, {},"scene.pcgBuildConfig"));publicationType_=static_cast<PcgPublicationType>(type);return Result<void>::success();}
Result<void> PcgBuildConfig::addHistory(int category,const std::string&sceneName,int64_t timestamp){if(category<0||category>6)return Result<void>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"build log category must be in range 0..6",{}, {},"scene.pcgBuildConfig"));history_.push_back({static_cast<PcgBuildLogCategory>(category),sceneName,timestamp});return Result<void>::success();}
Result<int> PcgBuildConfig::getHistoryCategory(uint64_t i)const{if(i>=history_.size())return Result<int>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"build history index is out of range",{}, {},"scene.pcgBuildConfig"));return Result<int>::success(static_cast<int>(history_[i].category));}
Result<std::string> PcgBuildConfig::getHistorySceneName(uint64_t i)const{if(i>=history_.size())return Result<std::string>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"build history index is out of range",{}, {},"scene.pcgBuildConfig"));return Result<std::string>::success(history_[i].sceneName);}
Result<int64_t> PcgBuildConfig::getHistoryTimestamp(uint64_t i)const{if(i>=history_.size())return Result<int64_t>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"build history index is out of range",{}, {},"scene.pcgBuildConfig"));return Result<int64_t>::success(history_[i].timestamp);}
void exposePcgBuildConfigBindings(ssq::Table&t){auto vm=t.getHandle();auto c=t.addClass("PcgBuildConfig",ssq::Class::Ctor<PcgBuildConfig()>());c.addFunc("setPublicationType",[vm](PcgBuildConfig*s,int v){return eve::script::projectResult(vm,s->setPublicationType(v));});c.addFunc("getPublicationType",[](const PcgBuildConfig*s){return s->getPublicationType();});c.addFunc("addHistory",[vm](PcgBuildConfig*s,int category,const std::string&n,int64_t ts){return eve::script::projectResult(vm,s->addHistory(category,n,ts));});c.addFunc("clearHistory",[](PcgBuildConfig*s){s->clearHistory();});c.addFunc("getHistoryCount",[](const PcgBuildConfig*s){return s->getHistoryCount();});c.addFunc("getHistoryCategory",[vm](const PcgBuildConfig*s,uint64_t i){return eve::script::projectResult(vm,s->getHistoryCategory(i),[](int v){return v;});});c.addFunc("getHistorySceneName",[vm](const PcgBuildConfig*s,uint64_t i){return eve::script::projectResult(vm,s->getHistorySceneName(i),[](const std::string&v){return v;});});c.addFunc("getHistoryTimestamp",[vm](const PcgBuildConfig*s,uint64_t i){return eve::script::projectResult(vm,s->getHistoryTimestamp(i),[](int64_t v){return v;});});}
}
