#include "scene/PcgGrowth.h"
#include "scene/SceneNodeRef.h"
#include "scene/Scene.h"
#include "common/SquirrelBinding.h"
#include <simplesquirrel/simplesquirrel.hpp>
#include <algorithm>
#include <cmath>
namespace eve::scene{namespace{template<class T>Result<T>bad(const char*m,const char*p){return Result<T>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,m,p));}float random01(std::uint32_t x){x^=x>>16;x*=0x7feb352du;x^=x>>15;x*=0x846ca68bu;x^=x>>16;return float(x>>8)*(1.f/16777216.f);}}
Result<void> PcgGrowth::configure(float a,float b,float v,float d){if(!std::isfinite(a)||!std::isfinite(b)||!std::isfinite(v)||!std::isfinite(d)||a<.1f||a>2||b<.1f||b>2||v<0||v>2||d<.5f||d>60)return bad<void>("growth configuration is outside Pcg ranges","scene.pcgGrowth.configure");startScale_=a;endScale_=b;variance_=v;duration_=d;return Result<void>::success();}
Result<void> PcgGrowth::start(float now,std::uint32_t seed){if(!std::isfinite(now))return bad<void>("start time must be finite","scene.pcgGrowth.start");startTime_=now;actualEnd_=endScale_+random01(seed)*variance_;scale_=startScale_;started_=true;finished_=false;dying_=false;return Result<void>::success();}
Result<float> PcgGrowth::advance(float now){if(!started_)return bad<float>("growth has not started","scene.pcgGrowth.advance");if(!std::isfinite(now)||now<startTime_)return bad<float>("time must be finite and monotonic","scene.pcgGrowth.advance");float t=std::min((now-startTime_)/duration_,1.f);scale_=startScale_+t*(actualEnd_-startScale_);finished_=t>=1;return Result<float>::success(scale_);}
Result<void> PcgGrowth::die(float now){if(!std::isfinite(now))return bad<void>("death time must be finite","scene.pcgGrowth.die");deathTime_=now+5;dying_=true;return Result<void>::success();}
Result<bool> PcgGrowth::shouldDestroy(float now)const{if(!std::isfinite(now))return bad<bool>("time must be finite","scene.pcgGrowth.destroy");return Result<bool>::success(dying_&&now>=deathTime_);}
Result<bool> applyPcgGrowth(PcgGrowth& g,SceneNodeRef& node,float now){auto due=g.shouldDestroy(now);if(!due)return Result<bool>::failure(due.status());if(due.value()){auto*s=node.getScene();if(!s||!s->removeNodeAt(node.getHostName(),node.getNodeId()))return bad<bool>("growth node cannot be removed","scene.pcgGrowth.node");return Result<bool>::success(true);}auto scale=g.advance(now);if(!scale)return Result<bool>::failure(scale.status());if(!node.setScale(scale.value(),scale.value(),scale.value()))return bad<bool>("growth node cannot be scaled","scene.pcgGrowth.node");return Result<bool>::success(false);}
void exposePcgGrowthBindings(ssq::Table&t){auto c=t.addClass("PcgGrowth",ssq::Class::Ctor<PcgGrowth()>());auto vm=t.getHandle();c.addFunc("configure",[vm](PcgGrowth*s,float a,float b,float v,float d){return eve::script::projectResult(vm,s->configure(a,b,v,d));});c.addFunc("start",[vm](PcgGrowth*s,float n,int seed){return eve::script::projectResult(vm,s->start(n,std::uint32_t(seed)));});c.addFunc("advance",[vm](PcgGrowth*s,float n){return eve::script::projectResult(vm,s->advance(n),[](float v){return Value(v);});});c.addFunc("die",[vm](PcgGrowth*s,float n){return eve::script::projectResult(vm,s->die(n));});c.addFunc("shouldDestroy",[vm](const PcgGrowth*s,float n){return eve::script::projectResult(vm,s->shouldDestroy(n),[](bool v){return Value(v);});});c.addFunc("getActualEndScale",[](const PcgGrowth*s){return s->getActualEndScale();});c.addFunc("getScale",[](const PcgGrowth*s){return s->getScale();});c.addFunc("getFinished",[](const PcgGrowth*s){return s->getFinished();});t.addFunc("applyPcgGrowth",[vm](PcgGrowth*g,SceneNodeRef*n,float now){auto r=g&&n?applyPcgGrowth(*g,*n,now):bad<bool>("growth and node are required","scene.pcgGrowth.node");return eve::script::projectResult(vm,std::move(r),[](bool v){return Value(v);});});}
}