"""Compile the canonical anime shader into the optional live-reload Squirrel payload."""
from pathlib import Path
import struct
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SOURCES = {
    "animeVertex": ROOT / "src/modules/graphics/shaders/mesh3d_toon.vert",
    "animeFragment": ROOT / "src/modules/stylize/shaders/anime_mesh.frag",
}


def main():
    lines = ["// Generated by compile_shader.py; edits belong in the canonical GLSL."]
    with tempfile.TemporaryDirectory() as directory:
        for name, source in SOURCES.items():
            binary = Path(directory) / (source.name + ".spv")
            subprocess.run(["glslc", str(source), "-o", str(binary)], check=True)
            subprocess.run(["spirv-val", str(binary)], check=True)
            data = binary.read_bytes()
            words = struct.unpack(f"<{len(data)//4}I", data)
            lines.append(name + " <- [" + ",".join(map(str, words)) + "];")
    target = HERE / "shaders/compiled.nut"
    target.parent.mkdir(exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main()
