"""Assemble generated terrain art and editable scene data; never draws source art."""
from pathlib import Path
import json
from PIL import Image

ROOT = Path(__file__).resolve().parent
ASSETS = ROOT / "assets"


def main():
    source = Image.open(ASSETS / "source/terrain.png").convert("RGB")
    atlas = Image.new("RGB", (256, 256))
    for y in range(4):
        for x in range(4):
            box = (round(x * source.width / 4) + 2, round(y * source.height / 4) + 2,
                   round((x + 1) * source.width / 4) - 2, round((y + 1) * source.height / 4) - 2)
            atlas.paste(source.crop(box).resize((64, 64), Image.Resampling.NEAREST), (x * 64, y * 64))
    atlas.save(ASSETS / "terrain.png")
    width, height = 22, 16
    ground = []
    for y in range(height):
        for x in range(width):
            gid = 2 if (x * 7 + y * 3) % 13 == 0 else 1
            if 3 <= x <= 12 and 3 <= y <= 12:
                gid = 3 if (x + y) % 4 else 4
            if 14 <= x <= 16:
                gid = 7 if (x + y) % 3 else 8
            if x == 13:
                gid = 15
            if 6 <= y <= 8 and x >= 12:
                gid = 11 if x <= 17 else 5
            ground.append(gid)
    raised = [0] * (width * height)
    for y in range(2, 5):
        for x in range(5, 11):
            raised[y * width + x] = 10
    for y in range(10, 12):
        for x in range(8, 10):
            raised[y * width + x] = 9
    data = {"schema": "evengine.hd2d.riverside", "version": 1,
            "unknownFields": "reject", "width": width, "height": height, "tileSize": 32,
            "layers": {"ground": ground, "raised": raised},
            "spawns": [{"id": "hero", "x": 6, "y": 8}, {"id": "scholar", "x": 10, "y": 7},
                       {"id": "guard", "x": 18, "y": 8}],
            "blockedGids": [7, 8, 15], "raisedHeight": 40}
    (ASSETS / "riverside.json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    # Same map data used by Squirrel, generated as literals to avoid a parallel handwritten layout.
    text = "// Generated by build_assets.py from the scene data above.\n"
    text += "riversideData <- " + json.dumps(data, separators=(",", ":")) + ";\n"
    # Squirrel table keys use =, JSON uses :. Quoted keys need bracket syntax.
    import re
    text = re.sub(r'"([^"\\]+)":', r'["\1"]=', text)
    (ROOT / "map-data.nut").write_text(text, encoding="utf-8")
    preview = Image.new("RGB", (width * 32, height * 32))
    for y in range(height):
        for x in range(width):
            gid = raised[y * width + x] or ground[y * width + x]
            tx, ty = (gid - 1) % 4, (gid - 1) // 4
            preview.paste(atlas.crop((tx * 64, ty * 64, tx * 64 + 64, ty * 64 + 64)).resize((32, 32), Image.Resampling.NEAREST), (x * 32, y * 32))
    preview.save(ASSETS / "map-layout-preview.png")


if __name__ == "__main__":
    main()
