"""Compile/embed the portable terrain material shaders."""

import shutil
import subprocess
from pathlib import Path

from compile_graphics_water_shaders import ROOT, spv_to_inc


SHADER = ROOT / "src" / "modules" / "procgen" / "shaders" / "terrain_material.frag"
WGSL_SHADER = SHADER.with_suffix(".frag.wgsl")


def main() -> None:
    glslc = shutil.which("glslc")
    if glslc is None:
        raise SystemExit("glslc was not found on PATH")
    binary = SHADER.with_suffix(".frag.spv")
    subprocess.run([glslc, str(SHADER), "-o", str(binary)], check=True)
    spv_to_inc(binary, "terrain_material_frag_spv", SHADER.parent / "terrain_material_frag_spv.inc")
    wgsl = WGSL_SHADER.read_text(encoding="utf-8")
    (SHADER.parent / "terrain_material_frag_wgsl.inc").write_text(
        '// Generated by compile_procgen_terrain_shader.py. Do not edit.\n'
        'inline constexpr const char terrain_material_frag_wgsl[] = R"eve_wgsl(\n'
        + wgsl
        + ')eve_wgsl";\n',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
