#!/usr/bin/env python3
"""Rebuild native sky programs and the thin-cloud GPU contract probe."""

from __future__ import annotations

import struct
import subprocess
import tempfile
from pathlib import Path

import utf8_stdio

ROOT = Path(__file__).resolve().parents[1]


def compile_header(programs: list[tuple[Path, str]], target: Path) -> None:
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "#include <vector>",
        "// Generated by scripts/compile_graphics_sky_shaders.py; do not edit.",
    ]
    with tempfile.TemporaryDirectory(prefix="eve-sky-shaders-") as temporary:
        for source, name in programs:
            output = Path(temporary) / (name + ".spv")
            subprocess.run(
                ["glslc", "--target-env=vulkan1.2", str(source), "-o", str(output)],
                check=True,
            )
            data = output.read_bytes()
            if len(data) % 4:
                raise ValueError("SPIR-V byte length is not word-aligned")
            words = struct.unpack(f"<{len(data) // 4}I", data)
            if not words or words[0] != 0x07230203:
                raise ValueError("Invalid SPIR-V magic")
            lines.append(f"inline const std::vector<uint32_t> {name}{{")
            for offset in range(0, len(words), 8):
                lines.append("    " + ", ".join(f"0x{word:08x}u" for word in words[offset : offset + 8]) + ",")
            lines.append("};")
    generated = "\n".join(lines) + "\n"
    if not target.exists() or target.read_text(encoding="utf-8") != generated:
        target.write_text(generated, encoding="utf-8")


def main() -> None:
    compile_header(
        [(ROOT / f"src/modules/graphics/shaders/sky_atmosphere.{stage}", f"sky_atmosphere_{stage}")
         for stage in ("vert", "frag")],
        ROOT / "src/modules/graphics/sky/SkyAtmosphereSpv.h",
    )
    compile_header(
        [(ROOT / f"src/modules/graphics/shaders/sky_view_lut.{stage}", f"sky_view_lut_{stage}")
         for stage in ("vert", "frag")],
        ROOT / "src/modules/graphics/sky/SkyViewLutSpv.h",
    )
    compile_header([(ROOT / "test/sky_wisps_probe.frag", "sky_wisps_probe_frag")], ROOT / "test/SkyWispsSpv.h")
    compile_header(
        [(ROOT / f"src/modules/graphics/shaders/sky_wisps.{stage}", f"sky_wisps_{stage}")
         for stage in ("vert", "frag")],
        ROOT / "src/modules/graphics/sky/SkyWispsSpv.h",
    )


if __name__ == "__main__":
    utf8_stdio.enable_utf8_stdio()
    main()
