#include "ui/PcgControllerSelection.h"
#include "common/SquirrelBinding.h"
#include <simplesquirrel/simplesquirrel.hpp>
namespace eve::ui {namespace {}
Result<void> PcgControllerSelection::add(const std::string&name,int type,const std::string&id){if(name.empty()||id.empty())return Result<void>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"controller name and widget id are required","ui.pcgControllerSelection"));rows_.push_back({name,id,type,false});return Result<void>::success();}
Result<bool> PcgControllerSelection::refresh(int current){int found=-1;for(size_t i=0;i<rows_.size();++i)if(rows_[i].controllerType==current){found=int(i);break;}if(found<0)return Result<bool>::success(false);for(size_t i=0;i<rows_.size();++i)rows_[i].visible=int(i)==found;selected_=found;return Result<bool>::success(true);}
Result<bool> PcgControllerSelection::getVisible(int i)const{if(i<0||i>=int(rows_.size()))return Result<bool>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"controller row index is out of range","ui.pcgControllerSelection"));return Result<bool>::success(rows_[size_t(i)].visible);}
Result<std::string> PcgControllerSelection::getWidgetId(int i)const{if(i<0||i>=int(rows_.size()))return Result<std::string>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"controller row index is out of range","ui.pcgControllerSelection"));return Result<std::string>::success(rows_[size_t(i)].widgetId);}
void exposePcgControllerSelectionBindings(ssq::Table&t){auto c=t.addClass("PcgControllerSelection",ssq::Class::Ctor<PcgControllerSelection()>());auto vm=t.getHandle();c.addFunc("add",[vm](PcgControllerSelection*s,const std::string&n,int type,const std::string&id){return eve::script::projectResult(vm,s->add(n,type,id));});c.addFunc("refresh",[vm](PcgControllerSelection*s,int type){return eve::script::projectResult(vm,s->refresh(type),[](bool v){return v;});});c.addFunc("getCount",[](const PcgControllerSelection*s){return s->getCount();});c.addFunc("getSelectedIndex",[](const PcgControllerSelection*s){return s->getSelectedIndex();});c.addFunc("getVisible",[vm](const PcgControllerSelection*s,int i){return eve::script::projectResult(vm,s->getVisible(i),[](bool v){return v;});});c.addFunc("getWidgetId",[vm](const PcgControllerSelection*s,int i){return eve::script::projectResult(vm,s->getWidgetId(i),[](std::string v){return v;});});}
}
