#include "ui/PcgPhotoModeSession.h"
#include "common/SquirrelBinding.h"
#include <simplesquirrel/simplesquirrel.hpp>
namespace eve::ui { namespace { Result<void> fail(const char*m){return Result<void>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,m,{}, {},"ui.pcgPhotoModeSession"));} }
Result<void> PcgPhotoModeSession::begin(const std::string&capturedJson,const std::string&savedJson,bool loadSaved,bool savedEver,int currentPipeline,int savedPipeline,const std::string&sceneName,int lightingProfile){
 if(active_)return fail("photo-mode session is already active");PcgPhotoModeValues captured;auto cr=captured.restoreJson(capturedJson);if(!cr.ok())return Result<void>::failure(cr.status());PcgPhotoModeValues working=captured;PcgPhotoModeLoadDecision decision=PcgPhotoModeLoadDecision::Current;
 if(loadSaved&&savedEver&&currentPipeline==savedPipeline&&!savedJson.empty()){PcgPhotoModeValues saved;auto sr=saved.restoreJson(savedJson);if(!sr.ok())return Result<void>::failure(sr.status());auto savedScene=saved.getString("m_lastSceneName");auto savedLighting=saved.getInt("m_selectedPcgLightingProfile");auto savedPcg=saved.getBool("m_isUsingPcgLighting");if(!savedScene.ok())return Result<void>::failure(savedScene.status());if(!savedLighting.ok())return Result<void>::failure(savedLighting.status());if(!savedPcg.ok())return Result<void>::failure(savedPcg.status());const bool lightingMatches=savedLighting.value()==lightingProfile&&savedPcg.value()==(lightingProfile>=0);if(savedScene.value()==sceneName&&lightingMatches){working=std::move(saved);decision=PcgPhotoModeLoadDecision::Saved;}else decision=PcgPhotoModeLoadDecision::SaveCurrent;}
 captured_=std::move(captured);working_=working;output_=working_;loadDecision_=decision;active_=true;restoreRequested_=removePhotoCameraRequested_=unfreezePlayerRequested_=false;++revision_;return Result<void>::success();
}
Result<void> PcgPhotoModeSession::replaceWorkingJson(const std::string&json){if(!active_)return fail("photo-mode session is not active");PcgPhotoModeValues candidate;auto r=candidate.restoreJson(json);if(!r.ok())return Result<void>::failure(r.status());working_=std::move(candidate);output_=working_;++revision_;return Result<void>::success();}
Result<void> PcgPhotoModeSession::end(bool resetOnDisable,bool applicationPlaying){if(!active_)return fail("photo-mode session is not active");removePhotoCameraRequested_=true;unfreezePlayerRequested_=true;restoreRequested_=resetOnDisable&&applicationPlaying;output_=restoreRequested_?captured_:working_;active_=false;++revision_;return Result<void>::success();}
Result<std::string> PcgPhotoModeSession::workingJson()const{return working_.snapshotJson();} Result<std::string> PcgPhotoModeSession::outputJson()const{return output_.snapshotJson();}
void exposePcgPhotoModeSessionBindings(ssq::Table&t){auto vm=t.getHandle();auto c=t.addClass("PcgPhotoModeSession",ssq::Class::Ctor<PcgPhotoModeSession()>());c.addFunc("begin",[vm](PcgPhotoModeSession*s,const std::string&a,const std::string&b,bool l,bool e,int p,int q,const std::string&n,int i){return eve::script::projectResult(vm,s->begin(a,b,l,e,p,q,n,i));});c.addFunc("replaceWorkingJson",[vm](PcgPhotoModeSession*s,const std::string&v){return eve::script::projectResult(vm,s->replaceWorkingJson(v));});c.addFunc("end",[vm](PcgPhotoModeSession*s,bool r,bool p){return eve::script::projectResult(vm,s->end(r,p));});c.addFunc("workingJson",[vm](const PcgPhotoModeSession*s){return eve::script::projectResult(vm,s->workingJson(),[](const std::string&v){return v;});});c.addFunc("outputJson",[vm](const PcgPhotoModeSession*s){return eve::script::projectResult(vm,s->outputJson(),[](const std::string&v){return v;});});c.addFunc("getActive",[](const PcgPhotoModeSession*s){return s->getActive();});c.addFunc("getRestoreRequested",[](const PcgPhotoModeSession*s){return s->getRestoreRequested();});c.addFunc("getRemovePhotoCameraRequested",[](const PcgPhotoModeSession*s){return s->getRemovePhotoCameraRequested();});c.addFunc("getUnfreezePlayerRequested",[](const PcgPhotoModeSession*s){return s->getUnfreezePlayerRequested();});c.addFunc("getLoadDecision",[](const PcgPhotoModeSession*s){return s->getLoadDecision();});c.addFunc("getRevision",[](const PcgPhotoModeSession*s){return s->getRevision();});}
}
