#include "ui/PcgPhotoModeColorPicker.h"
#include "common/SquirrelBinding.h"
#include <simplesquirrel/simplesquirrel.hpp>
#include <algorithm>
#include <cmath>
namespace eve::ui {namespace {Result<void> bad(){return Result<void>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,"color must be finite","ui.pcgPhotoModeColorPicker"));}bool finite4(float a,float b,float c,float d){return std::isfinite(a)&&std::isfinite(b)&&std::isfinite(c)&&std::isfinite(d);}}
bool PcgPhotoModeColorPicker::hdrActive()const noexcept{return hdr_&&(a_>1.f||a_<0.f);}
Result<void> PcgPhotoModeColorPicker::open(float r,float g,float b,float a,bool hdr){if(!finite4(r,g,b,a))return bad();float nr=r,ng=g,nb=b;if(hdr&&(a>1.f||a<0.f)){nr*=a;ng*=a;nb*=a;}r_=nr;g_=ng;b_=nb;a_=a;hdr_=hdr;open_=true;front_=true;return Result<void>::success();}
Result<void> PcgPhotoModeColorPicker::setLast(float r,float g,float b,float a){if(!finite4(r,g,b,a))return bad();lastR_=r;lastG_=g;lastB_=b;lastA_=a;return Result<void>::success();}
Result<void> PcgPhotoModeColorPicker::setChannel(float&dst,float v){if(!std::isfinite(v))return bad();dst=v;++revision_;return Result<void>::success();}
Result<void> PcgPhotoModeColorPicker::setRed(float v){return setChannel(r_,v);}Result<void> PcgPhotoModeColorPicker::setGreen(float v){return setChannel(g_,v);}Result<void> PcgPhotoModeColorPicker::setBlue(float v){return setChannel(b_,v);}Result<void> PcgPhotoModeColorPicker::setHdr(float v){return setChannel(a_,v);}
void PcgPhotoModeColorPicker::reset()noexcept{r_=lastR_;g_=lastG_;b_=lastB_;a_=lastA_;revision_+=5;}
float PcgPhotoModeColorPicker::getPreviewRed()const noexcept{return r_*(hdrActive()?a_:1.f);}float PcgPhotoModeColorPicker::getPreviewGreen()const noexcept{return g_*(hdrActive()?a_:1.f);}float PcgPhotoModeColorPicker::getPreviewBlue()const noexcept{return b_*(hdrActive()?a_:1.f);}float PcgPhotoModeColorPicker::getHdrSwatch()const noexcept{return std::clamp((a_+5.f)/10.f,0.f,1.f);}PcgUiRequestStatus PcgPhotoModeColorPicker::consumeBringToFront()noexcept{auto v=front_?PcgUiRequestStatus::Requested:PcgUiRequestStatus::None;front_=false;return v;}
void exposePcgPhotoModeColorPickerBindings(ssq::Table&t){auto c=t.addClass("PcgPhotoModeColorPicker",ssq::Class::Ctor<PcgPhotoModeColorPicker()>());auto vm=t.getHandle();c.addFunc("open",[vm](PcgPhotoModeColorPicker*s,float r,float g,float b,float a,bool h){return eve::script::projectResult(vm,s->open(r,g,b,a,h));});c.addFunc("setLast",[vm](PcgPhotoModeColorPicker*s,float r,float g,float b,float a){return eve::script::projectResult(vm,s->setLast(r,g,b,a));});c.addFunc("setFocusedName",&PcgPhotoModeColorPicker::setFocusedName);c.addFunc("close",[](PcgPhotoModeColorPicker*s){s->close();});c.addFunc("setRed",[vm](PcgPhotoModeColorPicker*s,float v){return eve::script::projectResult(vm,s->setRed(v));});c.addFunc("setGreen",[vm](PcgPhotoModeColorPicker*s,float v){return eve::script::projectResult(vm,s->setGreen(v));});c.addFunc("setBlue",[vm](PcgPhotoModeColorPicker*s,float v){return eve::script::projectResult(vm,s->setBlue(v));});c.addFunc("setHdr",[vm](PcgPhotoModeColorPicker*s,float v){return eve::script::projectResult(vm,s->setHdr(v));});c.addFunc("reset",[](PcgPhotoModeColorPicker*s){s->reset();});c.addFunc("getRed",[](const PcgPhotoModeColorPicker*s){return s->getRed();});c.addFunc("getGreen",[](const PcgPhotoModeColorPicker*s){return s->getGreen();});c.addFunc("getBlue",[](const PcgPhotoModeColorPicker*s){return s->getBlue();});c.addFunc("getAlpha",[](const PcgPhotoModeColorPicker*s){return s->getAlpha();});c.addFunc("getPreviewRed",[](const PcgPhotoModeColorPicker*s){return s->getPreviewRed();});c.addFunc("getPreviewGreen",[](const PcgPhotoModeColorPicker*s){return s->getPreviewGreen();});c.addFunc("getPreviewBlue",[](const PcgPhotoModeColorPicker*s){return s->getPreviewBlue();});c.addFunc("getHdrSwatch",[](const PcgPhotoModeColorPicker*s){return s->getHdrSwatch();});c.addFunc("getHdrEnabled",[](const PcgPhotoModeColorPicker*s){return s->getHdrEnabled();});c.addFunc("getOpen",[](const PcgPhotoModeColorPicker*s){return s->getOpen();});c.addFunc("getFocusedName",[](const PcgPhotoModeColorPicker*s){return s->getFocusedName();});c.addFunc("getChangeRevision",[](const PcgPhotoModeColorPicker*s){return s->getChangeRevision();});c.addFunc("consumeBringToFront",[](PcgPhotoModeColorPicker*s){return s->consumeBringToFront()==PcgUiRequestStatus::Requested;});}
}
