#include "ui/PcgPhotoModePanels.h"
#include "common/SquirrelBinding.h"
#include <simplesquirrel/simplesquirrel.hpp>
#include <algorithm>
#include <cmath>
namespace eve::ui { namespace {Result<void> invalid(const char*m,const char*p){return Result<void>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,m,p));}}
Result<void> PcgPhotoModePanels::select(int panel){if(panel<0||panel>=int(active_.size()))return invalid("photo-mode panel must be in range 0..6","ui.pcgPhotoModePanels.select");active_.fill(false);active_[size_t(panel)]=true;selected_=panel;scrollReset_=true;++revision_;return Result<void>::success();}
bool PcgPhotoModePanels::isActive(int panel)const noexcept{return panel>=0&&panel<int(active_.size())&&active_[size_t(panel)];}
PcgUiRequestStatus PcgPhotoModePanels::consumeScrollReset()noexcept{auto v=scrollReset_?PcgUiRequestStatus::Requested:PcgUiRequestStatus::None;scrollReset_=false;return v;}
Result<void> PcgPhotoModePanelButton::configure(float nr,float ng,float nb,float na,float sr,float sg,float sb,float sa){float v[]={nr,ng,nb,na,sr,sg,sb,sa};if(!std::all_of(std::begin(v),std::end(v),[](float x){return std::isfinite(x);}))return invalid("panel colors must be finite","ui.pcgPhotoModePanelButton.configure");nr_=nr;ng_=ng;nb_=nb;na_=na;sr_=sr;sg_=sg;sb_=sb;sa_=sa;return Result<void>::success();}
void exposePcgPhotoModePanelsBindings(ssq::Table&t){auto vm=t.getHandle();auto p=t.addClass("PcgPhotoModePanels",ssq::Class::Ctor<PcgPhotoModePanels()>());p.addFunc("select",[vm](PcgPhotoModePanels*s,int n){return eve::script::projectResult(vm,s->select(n));});p.addFunc("getSelected",[](const PcgPhotoModePanels*s){return s->getSelected();});p.addFunc("isActive",[](const PcgPhotoModePanels*s,int n){return s->isActive(n);});p.addFunc("consumeScrollReset",[](PcgPhotoModePanels*s){return s->consumeScrollReset()==PcgUiRequestStatus::Requested;});p.addFunc("getRevision",[](const PcgPhotoModePanels*s){return s->getRevision();});auto b=t.addClass("PcgPhotoModePanelButton",ssq::Class::Ctor<PcgPhotoModePanelButton()>());b.addFunc("configure",[vm](PcgPhotoModePanelButton*s,float a,float c,float d,float e,float f,float g,float h,float i){return eve::script::projectResult(vm,s->configure(a,c,d,e,f,g,h,i));});b.addFunc("setSelected",[](PcgPhotoModePanelButton*s,bool v){s->setSelected(v);});b.addFunc("getNormalR",[](const PcgPhotoModePanelButton*s){return s->getNormalR();});b.addFunc("getNormalG",[](const PcgPhotoModePanelButton*s){return s->getNormalG();});b.addFunc("getNormalB",[](const PcgPhotoModePanelButton*s){return s->getNormalB();});b.addFunc("getNormalA",[](const PcgPhotoModePanelButton*s){return s->getNormalA();});b.addFunc("getHighlightR",[](const PcgPhotoModePanelButton*s){return s->getHighlightR();});b.addFunc("getLayoutEnabled",[](const PcgPhotoModePanelButton*s){return s->getLayoutEnabled();});b.addFunc("getSelected",[](const PcgPhotoModePanelButton*s){return s->getSelected();});}
}
