#include "ui/PcgTooltip.h"
#include "common/SquirrelBinding.h"
#include <simplesquirrel/simplesquirrel.hpp>
#include <cmath>
namespace eve::ui {namespace {template<class T>Result<T>bad(const char*m){return Result<T>::failure(Diagnostic::error(DiagnosticCode::InvalidArgument,m,"ui.pcgTooltip"));}}
Result<void> PcgTooltipManager::configure(int mode,int theme,float delay,float bottom,float top,int wrap){if(mode<0||mode>2||theme<0||theme>1||!std::isfinite(delay)||!std::isfinite(bottom)||!std::isfinite(top)||delay<0||bottom<0||top<0||wrap<0)return bad<void>("invalid tooltip configuration");mode_=mode;theme_=theme;delay_=delay;bottomOffset_=bottom;topOffset_=top;wrapLimit_=wrap;hide();return Result<void>::success();}
Result<void> PcgTooltipManager::addTooltip(const std::string&id,const std::string&header,const std::string&text){if(id.empty())return bad<void>("tooltip id must not be empty");entries_.push_back({id,header,text});return Result<void>::success();}
Result<bool> PcgTooltipManager::removeTooltip(const std::string&q){if(q.empty())return bad<bool>("tooltip query must not be empty");for(auto it=entries_.begin();it!=entries_.end();++it)if(it->id.find(q)!=std::string::npos){entries_.erase(it);return Result<bool>::success(true);}return Result<bool>::success(false);}
bool PcgTooltipManager::accepts(int source)const noexcept{return source>=0&&source<=1&&(mode_==2||mode_==source);}
Result<bool> PcgTooltipManager::enter(int source,const std::string&q,float now){if(!std::isfinite(now)||now<0||q.empty()||source<0||source>1)return bad<bool>("invalid tooltip enter request");pending_=false;if(!accepts(source))return Result<bool>::success(false);for(const auto&e:entries_)if(e.id.find(q)!=std::string::npos){source_=source;header_=e.header;text_=e.text;showAt_=now+delay_;pending_=true;return Result<bool>::success(true);}return Result<bool>::success(false);}
Result<void> PcgTooltipManager::enterText(int source,const std::string&content,const std::string&header,float now){if(!std::isfinite(now)||now<0||source<0||source>1)return bad<void>("invalid tooltip enter request");pending_=false;if(!accepts(source))return Result<void>::success();source_=source;header_=header;text_=content;showAt_=now+delay_;pending_=true;return Result<void>::success();}
Result<void> PcgTooltipManager::exit(int source){if(source<0||source>1)return bad<void>("tooltip source must be UI or scene");if(accepts(source)){pending_=false;visible_=false;}return Result<void>::success();}
Result<void> PcgTooltipManager::tick(float now,float x,float y,float sw,float sh,bool input){if(!std::isfinite(now)||!std::isfinite(x)||!std::isfinite(y)||!std::isfinite(sw)||!std::isfinite(sh)||now<0||sw<=0||sh<=0)return bad<void>("invalid tooltip frame input");pivotX_=x/sw;float normalized=y/sh;pivotY_=normalized*(y<=sh*.5f?bottomOffset_:topOffset_);if(input){hide();return Result<void>::success();}if(pending_&&now>=showAt_){pending_=false;visible_=true;}return Result<void>::success();}
void exposePcgTooltipBindings(ssq::Table&t){auto c=t.addClass("PcgTooltipManager",ssq::Class::Ctor<PcgTooltipManager()>());auto vm=t.getHandle();c.addFunc("configure",[vm](PcgTooltipManager*s,int m,int th,float d,float b,float top,int w){return eve::script::projectResult(vm,s->configure(m,th,d,b,top,w));});c.addFunc("addTooltip",[vm](PcgTooltipManager*s,const std::string&i,const std::string&h,const std::string&x){return eve::script::projectResult(vm,s->addTooltip(i,h,x));});c.addFunc("removeTooltip",[vm](PcgTooltipManager*s,const std::string&q){return eve::script::projectResult(vm,s->removeTooltip(q),[](bool v){return v;});});c.addFunc("enter",[vm](PcgTooltipManager*s,int src,const std::string&q,float n){return eve::script::projectResult(vm,s->enter(src,q,n),[](bool v){return v;});});c.addFunc("enterText",[vm](PcgTooltipManager*s,int src,const std::string&text,const std::string&header,float n){return eve::script::projectResult(vm,s->enterText(src,text,header,n));});c.addFunc("exit",[vm](PcgTooltipManager*s,int src){return eve::script::projectResult(vm,s->exit(src));});c.addFunc("tick",[vm](PcgTooltipManager*s,float n,float x,float y,float w,float h,bool i){return eve::script::projectResult(vm,s->tick(n,x,y,w,h,i));});c.addFunc("hide",[](PcgTooltipManager*s){s->hide();});c.addFunc("getVisible",[](const PcgTooltipManager*s){return s->getVisible();});c.addFunc("getPending",[](const PcgTooltipManager*s){return s->getPending();});c.addFunc("getHeader",[](const PcgTooltipManager*s){return s->getHeader();});c.addFunc("getText",[](const PcgTooltipManager*s){return s->getText();});c.addFunc("getHeaderVisible",[](const PcgTooltipManager*s){return s->getHeaderVisible();});c.addFunc("getWrapEnabled",[](const PcgTooltipManager*s){return s->getWrapEnabled();});c.addFunc("getPivotX",[](const PcgTooltipManager*s){return s->getPivotX();});c.addFunc("getPivotY",[](const PcgTooltipManager*s){return s->getPivotY();});c.addFunc("getBackgroundR",[](const PcgTooltipManager*s){return s->getBackgroundR();});c.addFunc("getForeground",[](const PcgTooltipManager*s){return s->getForeground();});c.addFunc("getCount",[](const PcgTooltipManager*s){return s->getCount();});}
}
