# The exclude lists arrive '|'-joined (semicolons would be split by the shell
# running this -P script on Linux/macOS Ninja builds).
string(REPLACE "|" ";" exclude_dirs "${exclude_dirs}")
string(REPLACE "|" ";" exclude_files "${exclude_files}")

file(GLOB_RECURSE source_files ${CMAKE_CURRENT_SOURCE_DIR}/${module_name}/*.cpp)
file(GLOB_RECURSE sub_source_files ${CMAKE_CURRENT_SOURCE_DIR}/${module_name}/**/*.cpp)

set(file_list "")
foreach(file ${source_files})
    set(_eve_skip FALSE)
    foreach(exc ${exclude_dirs})
        if(file MATCHES "/${exc}/" OR file MATCHES "${exc}[\\/]+")
            set(_eve_skip TRUE)
        endif()
    endforeach()
    if(NOT _eve_skip)
        foreach(exc ${exclude_files})
            get_filename_component(_eve_fname "${file}" NAME)
            if(_eve_fname STREQUAL "${exc}")
                set(_eve_skip TRUE)
            endif()
        endforeach()
    endif()
    if(NOT _eve_skip)
        set(file_list "${file_list}${file}\n")
    endif()
endforeach()
foreach(file ${sub_source_files})
    set(_eve_skip FALSE)
    foreach(exc ${exclude_dirs})
        if(file MATCHES "/${exc}/" OR file MATCHES "${exc}[\\/]+")
            set(_eve_skip TRUE)
        endif()
    endforeach()
    if(NOT _eve_skip)
        foreach(exc ${exclude_files})
            get_filename_component(_eve_fname "${file}" NAME)
            if(_eve_fname STREQUAL "${exc}")
                set(_eve_skip TRUE)
            endif()
        endforeach()
    endif()
    if(NOT _eve_skip)
        set(file_list "${file_list}${file}\n")
    endif()
endforeach()

file(READ ${output_dir}/${module_name}_src.txt old_file_list)

if(NOT "${file_list}" STREQUAL "${old_file_list}")
    file(WRITE ${output_dir}/${module_name}_src.txt ${file_list})

    # rerun cmake
    message(WARNING "Rerun CMake to update source files")
    # execute_process(COMMAND ${CMAKE_COMMAND} --build . --target rebuild_cache WORKING_DIRECTORY ${build_dir})
endif()
