file(GLOB_RECURSE source_files ${CMAKE_CURRENT_SOURCE_DIR}/${module_name}/*.cpp)
file(GLOB_RECURSE sub_source_files ${CMAKE_CURRENT_SOURCE_DIR}/${module_name}/**/*.cpp)

# Semicolon-separated list of backend subdirectories to exclude from the module
# (e.g. "vulkan" for webgpu builds, "webgpu" for native builds). Entries match
# either an exact file name or a path fragment.
# Semicolon-separated list of exact file base names to exclude (e.g. Poco-heavy
# files trimmed from the WASM build).
set(file_list "")
foreach(file ${source_files})
    set(_eve_skip FALSE)
    foreach(exc ${exclude_dirs})
        if(file MATCHES "/${exc}/" OR file MATCHES "${exc}[\\/]+")
            set(_eve_skip TRUE)
        endif()
    endforeach()
    if(NOT _eve_skip)
        foreach(exc ${exclude_files})
            get_filename_component(_eve_fname "${file}" NAME)
            if(_eve_fname STREQUAL "${exc}")
                set(_eve_skip TRUE)
            endif()
        endforeach()
    endif()
    if(NOT _eve_skip)
        set(file_list "${file_list}${file}\n")
    endif()
endforeach()
foreach(file ${sub_source_files})
    set(_eve_skip FALSE)
    foreach(exc ${exclude_dirs})
        if(file MATCHES "/${exc}/" OR file MATCHES "${exc}[\\/]+")
            set(_eve_skip TRUE)
        endif()
    endforeach()
    if(NOT _eve_skip)
        foreach(exc ${exclude_files})
            get_filename_component(_eve_fname "${file}" NAME)
            if(_eve_fname STREQUAL "${exc}")
                set(_eve_skip TRUE)
            endif()
        endforeach()
    endif()
    if(NOT _eve_skip)
        set(file_list "${file_list}${file}\n")
    endif()
endforeach()

file(WRITE ${output_dir}/${module_name}_src.txt "${file_list}")
message(STATUS "detected source files: ${output_dir}/${module_name}_src.txt")
