include_guard(GLOBAL)
# Optional SDK libraries; uploads report Unsupported when the provider is absent.
option(EVENGINE_SHADER_ASSET_VALIDATION "Enable SPIR-V validation for external shader assets" ON)
function(eve_configure_shader_asset_validation target)
  if(NOT EVENGINE_SHADER_ASSET_VALIDATION)
    return()
  endif()
  find_path(EVE_SPIRV_TOOLS_INCLUDE spirv-tools/libspirv.hpp HINTS "$ENV{VULKAN_SDK}/Include")
  find_path(EVE_SPIRV_CROSS_INCLUDE spirv_cross/spirv_cross.hpp HINTS "$ENV{VULKAN_SDK}/Include")
  find_library(EVE_SPIRV_TOOLS_LIBRARY NAMES SPIRV-Tools HINTS "$ENV{VULKAN_SDK}/Lib")
  find_library(EVE_SPIRV_TOOLS_DEBUG NAMES SPIRV-Toolsd HINTS "$ENV{VULKAN_SDK}/Lib")
  find_library(EVE_SPIRV_CROSS_LIBRARY NAMES spirv-cross-core HINTS "$ENV{VULKAN_SDK}/Lib")
  find_library(EVE_SPIRV_CROSS_DEBUG NAMES spirv-cross-cored HINTS "$ENV{VULKAN_SDK}/Lib")
  if(EVE_SPIRV_TOOLS_INCLUDE AND EVE_SPIRV_CROSS_INCLUDE AND EVE_SPIRV_TOOLS_LIBRARY AND EVE_SPIRV_CROSS_LIBRARY)
    if(MSVC AND (NOT EVE_SPIRV_TOOLS_DEBUG OR NOT EVE_SPIRV_CROSS_DEBUG))
      message(STATUS "External shader uploads disabled: matching MSVC SPIR-V libraries unavailable")
      return()
    endif()
    target_include_directories(${target} SYSTEM PRIVATE "${EVE_SPIRV_TOOLS_INCLUDE}" "${EVE_SPIRV_CROSS_INCLUDE}")
    target_compile_definitions(${target} PRIVATE EVENGINE_SPIRV_ASSET_VALIDATION=1)
    if(MSVC AND EVE_SPIRV_TOOLS_DEBUG AND EVE_SPIRV_CROSS_DEBUG)
      target_link_libraries(${target} PRIVATE debug "${EVE_SPIRV_TOOLS_DEBUG}" optimized "${EVE_SPIRV_TOOLS_LIBRARY}"
        debug "${EVE_SPIRV_CROSS_DEBUG}" optimized "${EVE_SPIRV_CROSS_LIBRARY}")
    elseif(NOT MSVC)
      target_link_libraries(${target} PRIVATE "${EVE_SPIRV_TOOLS_LIBRARY}" "${EVE_SPIRV_CROSS_LIBRARY}")

    endif()
  endif()
endfunction()
