#include "hd2d_editing/Hd2dTarget.h"
#include "hd2d/Hd2d.h"
#include <exception>
#include <utility>
namespace eve::hd2d_editing{namespace{template<class T>EditorResult<T>fail(EditorStatus s,const char*r,std::string m){return EditorResult<T>::error(s,RuleId(r),std::move(m));}}
Hd2dDocumentRuntime::Hd2dDocumentRuntime()=default;Hd2dDocumentRuntime::~Hd2dDocumentRuntime()=default;
EditorResult<hd2d::Sprite3D*>Hd2dDocumentRuntime::publishSprite(const Hd2dDocumentTarget&document,hd2d::Hd2D*module,graphics::Graphics*graphics,graphics::Camera3D*camera,const IHd2dTextureResolver&textures){if(document.value().kind!="sprite"||!module||!graphics)return fail<hd2d::Sprite3D*>(EditorStatus::Rejected,"editor.hd2d.sprite","HD2D sprite publication requires sprite preset, module and Graphics");auto texture=textures.texture(document.value().sourceAsset);if(!texture.value||!*texture.value){EditorResult<hd2d::Sprite3D*>failed;failed.status=texture.status;failed.diagnostics=std::move(texture.diagnostics);return failed;}std::unique_ptr<hd2d::Sprite3D>candidate;try{candidate.reset(module->newSprite(graphics));if(!candidate)return fail<hd2d::Sprite3D*>(EditorStatus::Failed,"editor.hd2d.sprite-create","HD2D failed to create Sprite3D");const auto&v=document.value();candidate->setTexture(*texture.value);candidate->setFrameGrid(v.columns,v.rows);candidate->setFrameIndex(v.frame);candidate->setFlipX(v.flipX);candidate->setFlipY(v.flipY);candidate->setSize(v.size[0],v.size[1]);candidate->setTint(v.tint[0],v.tint[1],v.tint[2],v.tint[3]);candidate->setVisible(v.visible);candidate->setCamera(camera);candidate->play(v.animStart,v.animEnd,v.fps);}catch(const std::exception&e){return fail<hd2d::Sprite3D*>(EditorStatus::Failed,"editor.hd2d.sprite-build",e.what());}sprite_=std::move(candidate);tilemap_.reset();revision_=document.revision();return EditorResult<hd2d::Sprite3D*>::applied(sprite_.get());}
EditorResult<hd2d::TileMap3D*>Hd2dDocumentRuntime::publishTileMap(const Hd2dDocumentTarget&document,hd2d::Hd2D*module){if(document.value().kind!="tilemap"||!module)return fail<hd2d::TileMap3D*>(EditorStatus::Rejected,"editor.hd2d.tilemap","HD2D tilemap publication requires tilemap preset and module");std::unique_ptr<hd2d::TileMap3D>candidate;try{candidate.reset(module->newTileMap3D());if(!candidate)return fail<hd2d::TileMap3D*>(EditorStatus::Failed,"editor.hd2d.tilemap-create","HD2D failed to create TileMap3D");const auto&v=document.value();candidate->setSideDepth(v.sideDepth);candidate->setHeightScale(v.heightScale);candidate->setWallUV(v.wallUv[0],v.wallUv[1],v.wallUv[2],v.wallUv[3]);candidate->setTint(v.tint[0],v.tint[1],v.tint[2],v.tint[3]);}catch(const std::exception&e){return fail<hd2d::TileMap3D*>(EditorStatus::Failed,"editor.hd2d.tilemap-build",e.what());}tilemap_=std::move(candidate);sprite_.reset();revision_=document.revision();return EditorResult<hd2d::TileMap3D*>::applied(tilemap_.get());}
} // namespace eve::hd2d_editing
